// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package organize

import (
	"context"
	"github.com/ProtonMail/go-proton-api"
	"sync"
)

// Ensure, that ProtonClientMock does implement ProtonClient.
// If this is not the case, regenerate this file with moq.
var _ ProtonClient = &ProtonClientMock{}

// ProtonClientMock is a mock implementation of ProtonClient.
//
//	func TestSomethingThatUsesProtonClient(t *testing.T) {
//
//		// make and configure a mocked ProtonClient
//		mockedProtonClient := &ProtonClientMock{
//			CreateLabelFunc: func(ctx context.Context, req proton.CreateLabelReq) (proton.Label, error) {
//				panic("mock out the CreateLabel method")
//			},
//			GetLabelsFunc: func(ctx context.Context, labelTypes ...proton.LabelType) ([]proton.Label, error) {
//				panic("mock out the GetLabels method")
//			},
//		}
//
//		// use mockedProtonClient in code that requires ProtonClient
//		// and then make assertions.
//
//	}
type ProtonClientMock struct {
	// CreateLabelFunc mocks the CreateLabel method.
	CreateLabelFunc func(ctx context.Context, req proton.CreateLabelReq) (proton.Label, error)

	// GetLabelsFunc mocks the GetLabels method.
	GetLabelsFunc func(ctx context.Context, labelTypes ...proton.LabelType) ([]proton.Label, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateLabel holds details about calls to the CreateLabel method.
		CreateLabel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req proton.CreateLabelReq
		}
		// GetLabels holds details about calls to the GetLabels method.
		GetLabels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LabelTypes is the labelTypes argument value.
			LabelTypes []proton.LabelType
		}
	}
	lockCreateLabel sync.RWMutex
	lockGetLabels   sync.RWMutex
}

// CreateLabel calls CreateLabelFunc.
func (mock *ProtonClientMock) CreateLabel(ctx context.Context, req proton.CreateLabelReq) (proton.Label, error) {
	if mock.CreateLabelFunc == nil {
		panic("ProtonClientMock.CreateLabelFunc: method is nil but ProtonClient.CreateLabel was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req proton.CreateLabelReq
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateLabel.Lock()
	mock.calls.CreateLabel = append(mock.calls.CreateLabel, callInfo)
	mock.lockCreateLabel.Unlock()
	return mock.CreateLabelFunc(ctx, req)
}

// CreateLabelCalls gets all the calls that were made to CreateLabel.
// Check the length with:
//
//	len(mockedProtonClient.CreateLabelCalls())
func (mock *ProtonClientMock) CreateLabelCalls() []struct {
	Ctx context.Context
	Req proton.CreateLabelReq
} {
	var calls []struct {
		Ctx context.Context
		Req proton.CreateLabelReq
	}
	mock.lockCreateLabel.RLock()
	calls = mock.calls.CreateLabel
	mock.lockCreateLabel.RUnlock()
	return calls
}

// GetLabels calls GetLabelsFunc.
func (mock *ProtonClientMock) GetLabels(ctx context.Context, labelTypes ...proton.LabelType) ([]proton.Label, error) {
	if mock.GetLabelsFunc == nil {
		panic("ProtonClientMock.GetLabelsFunc: method is nil but ProtonClient.GetLabels was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		LabelTypes []proton.LabelType
	}{
		Ctx:        ctx,
		LabelTypes: labelTypes,
	}
	mock.lockGetLabels.Lock()
	mock.calls.GetLabels = append(mock.calls.GetLabels, callInfo)
	mock.lockGetLabels.Unlock()
	return mock.GetLabelsFunc(ctx, labelTypes...)
}

// GetLabelsCalls gets all the calls that were made to GetLabels.
// Check the length with:
//
//	len(mockedProtonClient.GetLabelsCalls())
func (mock *ProtonClientMock) GetLabelsCalls() []struct {
	Ctx        context.Context
	LabelTypes []proton.LabelType
} {
	var calls []struct {
		Ctx        context.Context
		LabelTypes []proton.LabelType
	}
	mock.lockGetLabels.RLock()
	calls = mock.calls.GetLabels
	mock.lockGetLabels.RUnlock()
	return calls
}
